# Generated by Django 6.0.3 on 2026-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('AZN', 'Azerbaijani Manat'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='AZN', max_length=3),
        ),
    ]
